CREATE DATABASE IF NOT EXISTS db_citas;
USE db_citas;

CREATE TABLE IF NOT EXISTS citas (
  id INT NOT NULL AUTO_INCREMENT,
  cliente_id INT DEFAULT NULL,
  servicio_id INT DEFAULT NULL,
  barbero_id INT DEFAULT NULL,
  fecha_hora DATETIME DEFAULT NULL,
  precio DECIMAL(10,2) DEFAULT NULL,
  estado VARCHAR(50) DEFAULT NULL,
  metodo_pago VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
